const express = require('express')
require('express-async-errors')
const app = express()
const cors = require('cors')

const userRouter = require('./routes/users')
const loginRouter = require('./routes/login')
const verifyRouter = require('./routes/verify')
const resetRouter = require('./routes/reset')
const tagsRouter = require('./routes/tags')
const photosRouter = require('./routes/photos')
const viewsRouter = require('./routes/views')
const likesRouter = require('./routes/likes')
const matchRouter = require('./routes/matches')
const reportsRouter = require('./routes/reports')
const blocksRouter = require('./routes/blocks')
const messagesRouter = require('./routes/messages')
const notifRouter = require('./routes/notifications')

const middleware = require('./utils/middleware')

app.use(cors())
app.use(express.static('build'))
app.use(express.json({ limit: '10mb', extended: true }))
app.use(express.urlencoded({ limit: '10mb', extended: true }))
app.use(middleware.requestLogger)
app.use(middleware.tokenExtractor)

app.use('/api/users', userRouter)
app.use('/api/login', loginRouter)
app.use('/api/verify', verifyRouter)
app.use('/api/reset', resetRouter)
app.use('/api/tags', tagsRouter)
app.use('/api/photos', photosRouter)
app.use('/api/views', viewsRouter)
app.use('/api/likes', likesRouter)
app.use('/api/matches', matchRouter)
app.use('/api/reports', reportsRouter)
app.use('/api/blocks', blocksRouter)
app.use('/api/messages', messagesRouter)
app.use('/api/notif', notifRouter)
app.use('/*', express.static('build'))

app.use(middleware.unknownEndpoint)
app.use(middleware.errorHandler)

module.exports = app
